var new_lang = {
lt1: 	'Preparato efficace contro l’ipertensione!',
lt2: 	'organico',
lt3: 	'3567 persone <br> l’hanno ordinato oggi',
lt4: 	'Prenotare il servizio di richiamata ',
lt5: 	'Prenotare il servizio di richiamata ',
lt6: 	'la pressione è nella norma<br>dalla prima assunzione e per sempre',
lt7: 	'Salvatevi dalla morte<br>per infarto e ictus!',
lt8: 	'La pressione si stabilizza<br>per la prima volta in 6 ore<br>grazie al biflavonide',
lt9: 	'Ripristina<br>il tono e l’elasticità<br>dei vasi sanguigni con un solo ciclo',
lt10: 	'Sicuro a qualsiasi età<br>efficace al primo, secondo e terzo<br>stadio dell’ipertensione',
lt11: 	'La quantità di confezioni nel<br>magazzino più vicino è limitata:',
lt12: 	'Confezioni',
lt13: 	'Prezzo',
lt14: 	'per l’esposrtazione:',
lt15: 	'Prezzo con',
lt16: 	'lo sconto:',
lt17: 	'Nazione',
lt18: 	'Inserite il vostro nome',
lt19: 	'Inserite il vostro numero di telefono',
lt20: 	'Ordinare',
lt21: 	'Controllatevi!<br>Avete almeno uno di questi sintomi?',
lt22: 	'Mal di <br>test',
lt23: 	'Punti neri<br>davanti agli occhi (mosche)',
lt24: 	'Apatia,<br>nervosismo,<br>sonnolenza',
lt25: 	'Vista<br>offuscata',
lt26: 	'Sudorazione',
lt27: 	'Battito cardiaco<br>velocizzato',
lt28: 	'Stanchezza<br>cronica',
lt29: 	'Viso<br>gonfio',
lt30: 	'Perdita di sensibilià<br>delle dita',
lt31: 	'Sbalzi<br>di pressione',
lt32: 	'SI TRATTA DI IPERTENSIONE!',
lt33: 	'Importante da sapere!<br>il 67% di chi soffre di ipertensione in<br>Italia<br>non sospetta neanche<br>di essere<br>malato.',
lt34: 	'In cosa è pericolosa l’ipertensione?',
lt35: 	'Le conseguenze dell’ipertensione sono più pericolose delle malattie oncologiche e della tubercolosi prese insieme. .<br>Nell’  89% dei casi l’ipertensione si conclude in infarto. Nei vasi sanguigni si forma un tappo.<br>C’è grande possibilità di ritrovarsi con un ictus.',
lt36: 	'Le conseguenze sono particolarmente pericolose in caso si fumi, si consumino bevande alcoliche, si segua una cattiva alimentazione, uno stile di vita sedentario, forti stress, un alto livello di colesterolo. Le persone con peso in eccesso soffrono di ipertensione molto più frequentemente.',
lt37: 	'IMPORTANTE!<br>L’ipertensione si sviluppa molto rapidamente e si sta diffondendo sempre più, minaccia di morte una persona su cinque. Iniziate a curarvi ora e sarete completamente in salute. ',
lt38: 	'Scoperta sensazionale degli studiosi',
lt39: 	'Nella creazione di un preparato per la cura e per la prevenzione, gli scienziati italiani del Centro Flebologico Statale hanno speso 8 anni. La scoperta dell’anno è stata nominata al premio medico internazionale  Gairdner. Diversi test a più livelli hanno dimostrato l’efficacia del preparato, grazie a ciò gli studiosi hanno ricevuto tutte le licenze e i certificati di qualità e i patrocino statale.',
lt40: 	'Tra gli ingredienti di ReCardio© <span>troviamo i seguenti elementi:</span>',
lt41: 	'Ortica',
lt42: 	'Contiene una grande quantità di vitamine, acidi, e componenti attivi. Super efficace nella cura delle malattie del cuore. Aiuta ad eliminare il nervosismo, migliora il lavoro del cuore, migliora la circolazione sanguigna, scioglie gli ammassi sanguigni e rinforza la capacità di lasciar passare il sangue dei vasi sanguigni.',
lt43: 	'Biancospino',
lt44: 	'Tonifica i muscoli del cuore, ha un’azione che allarga i vasi sanguigni, previene la formazione di placche e migliora i valori del sangue.  Stabilizza il livello di colesterolo nel sangue.',
lt45: 	'Abbassa la pressione sanguigna nei tessuti e negli apparati dell’organismo, aiuta ad eliminare i liquidi in eccesso.',
lt46: 	'Riboflavina, vitamina B2',
lt47: 	'Una delle vitamine più importanti per l’organismo umano. Necessaria per la formazione di globuli rossi e anticorpi, per far respirare le cellule e per farle crescere.',
lt48: 	'Tiamina, Vitamina B1',
lt49: 	'Componente senza il quale il sistema nervoso non può funzionare stabilmente, ha effetti rilassanti. Migliora la circolazione sanguigna e  partecipa all’Emopoiesi',
lt50: 	'Il parere dell’esperto',
lt51: 	'Confermo!<br>Il più importante nemico dell’ipertensione — è il bioflavonide.  Viene estratto solo dalla resina e dalla corteccia del larice selvatico. E’ presente in praticamente tutti i preparati contro l’ipertensione.<br> Ma, c’è un ma! Per la maggior parte dei produttori è sufficiente inserirlo in quantità misere! Questo vuol dire che l’effetto può farsi attendere per anni.  A quanto mi è dato sapere, l’unico preparato che utilizza una quantità adatta di biofavonide è ReCardio©.<br> Ne ho visto la formula e conosco il parere di diversi esperti. Persone rispettabili. Raccomando il preparato ai miei pazienti e li sgrido se si urano a modo loro o prendono quello che  «ha consigliato l’amica», «l’ho letto su internet» , «l’ho visto<br>in un programma». E’ sbagliato! Bisogna combattere l’ipertensione sono con prootti controllati! In cui credono i dottori,  con l’aiuto dei quali il vostro dolore scomparirà per sempre.',
lt52: 	'Gennaro Salvemini<br>Dottore di prima categoria, dottore in scienze mediche<br>stage lavorativo 30 anni</p>',
lt53: 	'Efficacia',
lt54: 	'confermata<br> da test clinici',
lt55: 	'I test clinici sono stati effettuati nel 2016 all’interno dell’Istituto di Cardiologia. Quattro gruppi di volontari hanno preso parte ai testi clinici per 25 giorni.<br> Il primo  gruppo di carattere ipertonico ha assunto  ReCardio©. <br> Il secondo gruppo,  uomini e donne con un problema analogo hanno preso un,  “placebo”.',
lt56: 	'Risultato dei test',
lt57: 	'PLACEBO',
lt58: 	'Stabilizzazione della pressione<br> arteriosa',
lt59: 	'Eliminazione dei trombi nelle vene',
lt60: 	'Eliminazione dell’aritmia',
lt61: 	'Stabilizzazione della pressione<br> arteriosa',
lt62: 	'Eliminazione dei trombi nelle vene',
lt63: 	'Eliminazione dell’aritmia',
lt64: 	'Recensioni delle persone che ne hanno provato l’effetto',
lt65: 	'Prendendo come esempio mia sorella ho capito che l’abbassamento della pressione arteriosa attraverso le pillole porta all’insulto ischemico, l’infarto del cervello. I medici le hanno salvato la vita ma non è mai più tornata come prima. Quando anche io ho iniziato a soffrire di pressione quindi sapevo già di dover cercare una cura naturale. Il mio dottore, una donna molto saggia, mi ha prescritto ReCardio. Le sono molto grata. Sono 4 anni che non mi sento più come una malata d’ipertensione. Sono una persona completamente in salute e non ho paura di infarti e ictus. Auguro tanta salute a tutti! ',
lt66: 	'Emilia, Vicenza, 61 anni',
lt67: 	'Qualche anno fa mi sono curata in una struttura specializzata. Stavano per l’appunto testando un preparato contro l’ipertensione. Io ovviamente ero impaurita. Ma che fare? Nessun medicinale mi aiutava, così mi sono decisa. Fortunatamente sono capitata nel gruppo a cui hanno dato  ReCardio,e non il “placebo”. In due ore la pressione già era nella norma. E col passare del tempo ho iniziato a sentirmi sempre meglio! Sono molto contenta di aver partecipato ai test. Ora la mia salute è sempre nella norma.',
lt68: 	'Loredana, Milano, 47 anni',
lt69: 	'Ho 51 anni. 3 anni fa al policlinico mi hanno diagnosticato l’ipertensione, fischietti al cuore e così via. Ho sofferto ma non ho fatto nulla. Poi sei mesi fa ho avuto un microictus. Ed allora ho iniziato ad avere paura, e mi sono rifiutato di prendere le pillole oltre. I prodotti chimici fanno male, non è una novità. Tuttavia non sapevo cosa fare. Fortunatamente un incontro casuale con un amico mi ha fatto fare la conoscenza di  ReCardio. Ora, come saprete da soli, NON HO NULLA. La pressione è nella norma, sono in salute come un toro!',
lt70: 	'Ivano, Roma, 51 anni',
lt71: 	'Vantaggi',
lt72: 	'Aiuto rapido.',
lt73: 	'Già nelle prime 6 ore dopo l’assunzione la pressione si stabilizza!',
lt74: 	'Non provoca improvvisi <br>sbalzi di pressione.',
lt75: 	'Regola in maniera armonica il funzionamento del cuore.',
lt76: 	'Cura complessiva.',
lt77: 	'Elimina l’angina pectoris, l’aritmia, la nevrosi, migliora la memoria, ridona una comunicazione e un movimento corretto dopo un ictus.',
lt78: 	'Azione efficace senza effetti collaterali.',
lt79: 	'Le cellule vive dei vegetali sono completamente compatibili con quelle umane.',
lt80: 	'Posologia',
lt81: 	'Assumere 100 ml di preparato due volte al giorno .<br> Si raccomanda un ciclo di 40 giorni.<br> Istruzioni più dettagliate sono presenti sulla confezione. ',
lt82: 	'Inserite i vostri dati nel modulo sottostante:',
lt83: 	'Vitamina В6',
lt84: 'Tra gli ingredienti di ReCardio<sup class="sup_f_size">©</sup> <span class="lt40">ci sono i seguenti elementi:</span>'
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};